# **Business Understanding**

**About the data**
This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.



[data source](https://archive.ics.uci.edu/dataset/352/online+retail)

#### **Load Libraries**

In [22]:

import joblib # will help us package our final model
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

#### **Load Data**

In [29]:
df = pd.read_excel("data/Online Retail.xlsx")

# **Data Understanding**

In [4]:
rows, columns = df.shape
output = f" Records: {rows} and features: {columns} " 
print(output)

 Records: 541909 and features: 8

Checking for missing values

In [5]:
display(df.isna().sum()* 100 / len(df))

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

Cehcking for dupliates

In [6]:
# Get all rows where values appear more than once
all_duplicate_rows = df[df.duplicated(keep=False)]   
len(all_duplicate_rows)

10147

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [9]:
df["cost"] = df["Quantity"] * df["UnitPrice"]

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,cost
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [11]:
all_duplicate_rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [12]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,cost
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   cost         541909 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(3), str(1)
memory usage: 37.2+ MB

#### **Univariate Analysis**

In [14]:
df["UnitPrice"].info()

<class 'pandas.Series'>
RangeIndex: 541909 entries, 0 to 541908
Series name: UnitPrice
Non-Null Count   Dtype
--------------   -----
541909 non-null  float64
dtypes: float64(1)
memory usage: 4.1 MB

In [15]:
df["UnitPrice"].describe()

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

In [16]:
df[["UnitPrice" , "cost"]].describe()

           UnitPrice           cost
count  541909.000000  541909.000000
mean        4.611114      17.987795
std        96.759853     378.810824
min    -11062.060000 -168469.600000
25%         1.250000       3.400000
50%         2.080000       9.750000
75%         4.130000      17.400000
max     38970.000000  168469.600000

In [17]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'cost'],
      dtype='str')

#### **Multivariate**

In [18]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,cost
count,541909.000000,541909,541909.000000,406829.000000,541909.000000
mean,9.552250,2011-07-04 13:34:57.156386,4.611114,15287.690570,17.987795
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,-168469.600000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,3.400000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,9.750000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,17.400000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,168469.600000
std,218.081158,NaN,96.759853,1713.600303,378.810824

In [21]:
df.describe(include = 'object')

/tmp/ipykernel_19609/1466716981.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = 'object')

,InvoiceNo,StockCode,Description,Country
count,541909,541909,540455,541909
unique,25900,4070,4223,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom
freq,1114,2313,2369,495478

Current problems:
- Outliers are present
- Some values being large they tend to affect the general scale & MCTs
- Missing values & duplicate (this could be normal)

# **Data Preparation**

Cleaning the data

In [30]:
display(df.isna().sum()* 100 / len(df))

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

Note:
- InvoiceNo: *Invoice* number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation.

In [37]:
before_cleaning = len(df) # size of dataset before clearning
#  drpo missing values
df_2 = df.dropna(subset=["CustomerID"]) # dropped all missing values in cusotmer id

df_2 = df_2[~df_2["InvoiceNo"].astype(str).str.startswith("C")]
after_cleaning = len(df_2)
after_cleaning
percentage_loss = ((before_cleaning - after_cleaning)/ before_cleaning)*100

summary = f" we have dropped {(percentage_loss):.2f}% of the data"
print(summary)

 we have dropped 26.57% of the data

In [39]:
display(df_2.isna().sum()* 100 / len(df_2))

InvoiceNo      0.0
StockCode      0.0
Description    0.0
Quantity       0.0
InvoiceDate    0.0
UnitPrice      0.0
CustomerID     0.0
Country        0.0
dtype: float64

#### Defining the Recency-Frequency-Monetary Analysis(RFM) based on customers, whereby the customer will represent one row

In [42]:
df_2["CustomerID"].unique()

array([17850., 13047., 12583., ..., 13298., 14569., 12713.], shape=(4339,))

In [45]:
df_2.info()

<class 'pandas.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[us]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 27.3+ MB

In [49]:
df_2["CustomerID"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 397924, dtype: float64

In [ ]:
# filtering the transaction of customer with ID; 17850
df_client_one = df_2[df_2["CustomerID"] == 17850]
df_client_one

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
4540,536790,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 15:26:00,7.65,17850.0,United Kingdom
4541,536790,22803,IVORY EMBROIDERED QUILT,3,2010-12-02 15:26:00,35.75,17850.0,United Kingdom
4542,536790,21730,GLASS STAR FROSTED T-LIGHT HOLDER,12,2010-12-02 15:26:00,4.25,17850.0,United Kingdom
4543,536791,22632,HAND WARMER RED POLKA DOT,12,2010-12-02 15:27:00,1.85,17850.0,United Kingdom
4544,536791,22633,HAND WARMER UNION JACK,12,2010-12-02 15:27:00,1.85,17850.0,United Kingdom

In [48]:
df_client_one["InvoiceNo"].describe()

count        297
unique        34
top       536750
freq          19
Name: InvoiceNo, dtype: int64

In [50]:
df_client_one[df_client_one["InvoiceNo"]==536750]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
4161,536750,85123A,WHITE HANGING HEART T-LIGHT HOLDER,12,2010-12-02 14:04:00,2.55,17850.0,United Kingdom
4162,536750,71053,WHITE METAL LANTERN,12,2010-12-02 14:04:00,3.39,17850.0,United Kingdom
4163,536750,84406B,CREAM CUPID HEARTS COAT HANGER,6,2010-12-02 14:04:00,2.75,17850.0,United Kingdom
4164,536750,15056BL,EDWARDIAN PARASOL BLACK,6,2010-12-02 14:04:00,4.95,17850.0,United Kingdom
4165,536750,20679,EDWARDIAN PARASOL RED,6,2010-12-02 14:04:00,4.95,17850.0,United Kingdom
4166,536750,37370,RETRO COFFEE MUGS ASSORTED,6,2010-12-02 14:04:00,1.06,17850.0,United Kingdom
4167,536750,21871,SAVE THE PLANET MUG,6,2010-12-02 14:04:00,1.06,17850.0,United Kingdom
4168,536750,21071,VINTAGE BILLBOARD DRINK ME MUG,6,2010-12-02 14:04:00,1.06,17850.0,United Kingdom
4169,536750,21068,VINTAGE BILLBOARD LOVE/HATE MUG,6,2010-12-02 14:04:00,1.06,17850.0,United Kingdom
4170,536750,82483,WOOD 2 DRAWER CABINET WHITE FINISH,4,2010-12-02 14:04:00,4.95,17850.0,United Kingdom
4171,536750,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,2010-12-02 14:04:00,6.95,17850.0,United Kingdom
4172,536750,82482,WOODEN PICTURE FRAME WHITE FINISH,6,2010-12-02 14:04:00,2.10,17850.0,United Kingdom
4173,536750,82494L,WOODEN FRAME ANTIQUE WHITE,6,2010-12-02 14:04:00,2.55,17850.0,United Kingdom
4174,536750,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,6,2010-12-02 14:04:00,1.65,17850.0,United Kingdom
4175,536750,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-02 14:04:00,3.39,17850.0,United Kingdom
4176,536750,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-02 14:04:00,3.39,17850.0,United Kingdom
4177,536750,22752,SET 7 BABUSHKA NESTING BOXES,4,2010-12-02 14:04:00,7.65,17850.0,United Kingdom
4178,536750,22803,IVORY EMBROIDERED QUILT,2,2010-12-02 14:04:00,35.75,17850.0,United Kingdom
4179,536750,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,2010-12-02 14:04:00,4.25,17850.0,United Kingdom

In [51]:
df["InvoiceDate"].describe()

count                        541909
mean     2011-07-04 13:34:57.156386
min             2010-12-01 08:26:00
25%             2011-03-28 11:34:00
50%             2011-07-19 17:17:00
75%             2011-10-19 11:27:00
max             2011-12-09 12:50:00
Name: InvoiceDate, dtype: object

In [52]:
df_2["InvoiceDate"].max()

Timestamp('2011-12-09 12:50:00')

In [56]:
""""
NOTe:
- if a client makes a purchase on the last day of the transactions their receny may be calcuated as 0 to counter this we add one day to the last day using the pd.Timedelta(days = 1)
Helps calcluate the date since last purchase
"""
shop_financial_year_close_running = df_2["InvoiceDate"].max() + pd.Timedelta(days = 1) 
shop_financial_year_close_running

Timestamp('2011-12-10 12:50:00')

creating our Recency-Frequecy-Monetary dataframe createion

In [58]:
df_2.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [59]:
df_2["TotalPrice"] = df_2["Quantity"] * df_2["UnitPrice"]

In [60]:
df_2.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [66]:
rfm = df_2.groupby("CustomerID").agg(
    Recency = ("InvoiceDate", lambda d: (shop_financial_year_close_running - d.max()).days ),
    Frequency= ("InvoiceNo", "nunique"),
    Monetary = ("TotalPrice", "sum")
)

In [67]:
df_2["CustomerID"].nunique()

4339

In [68]:
len(rfm) # this dataframe is composed of purely unique customer purcahase / RFM

4339

In [69]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40

In [73]:
rows, columns = rfm.shape
output = f"we currently have {rows} customers their respective  RFM scores are in {columns} columns "
print(output)

we currently have 4339 customers their respective  RFM scores are in 3 columns

In [74]:
rfm.describe()

           Recency    Frequency       Monetary
count  4339.000000  4339.000000    4339.000000
mean     92.518322     4.271952    2053.793018
std     100.009747     7.705493    8988.248381
min       1.000000     1.000000       0.000000
25%      18.000000     1.000000     307.245000
50%      51.000000     2.000000     674.450000
75%     142.000000     5.000000    1661.640000
max     374.000000   210.000000  280206.020000

# **Data Modeling**

# **Evaluation**

# **Deployment**